apiVersion: v1
kind: ReplicationController
metadata:
  name: rc-nginx
spec:
  replicas: 3 # 배포갯수
  selector: # 템플릿에 lable이 꼭 포함되어야 됨
    app: webui
  template:
    # 컨테이너 템플릿(Pod 정보)
    metadata:
      name: nginx-pod
      labels:
        app: webui
    spec:
      containers:
      - name: nginx-container
        image: nginx:1.14